disable scanf_s(), vscanf_s(), etc
These functions don't build due to missing definitions for _IO_FILE
and _IO_va_list types:

 | stdio_fmt_s.c: At top level:
 | stdio_fmt_s.c:380:27: error: unknown type name '_IO_FILE'; did you mean '__FILE'?
 |   380 | extern int gnu_vfscanf_s (_IO_FILE *s, const char *format,
 |       |                           ^~~~~~~~
 |       |                           __FILE
 | stdio_fmt_s.c:381:9: error: unknown type name '_IO_va_list'; did you mean 'va_list'?
 |   381 |         _IO_va_list argptr,
 |       |         ^~~~~~~~~~~
 |       |         va_list

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>